site_name: Pointslocal Admin Documentation

pages:
- Home: index.md
- Creating Pages:
  - Stream Templates: content_templates.md
  - Element Templates (Components): content_element_templates.md
- Events:
  - Managing Events:
    - Managing Events: events_events.md
    - Managing User-submitted Content: events_ugc.md
  - Managing Categories:
    - Managing Categories and Stock Art: events_categories_art.md
  - Managing Venues: events_venues.md

  - Managing Editorial Packages: events_packages.md

  - Exporting Events: events_exports.md
  - Importing Events: events_imports.md
  - Other Content Types:
      - Sports: gameplan_exports.md

- Gameplan (Sports):
  - Introducing Gameplan: gameplan_home.md
  - Creating and Managing Sports: gameplan_sports.md
  - Print Exports: gameplan_exports.md
- Stories:
  - Managing and Creating Stories: stories_create.md
  - Managing Story Sources And Imports: stories_sources.md
- Advanced and Administrative:
  - Site Configuration: admin_configuration.md
  - Managing Ontology: admin_ontology.md
  - Setting API defaults: advanced_api_defaults.md
  - Creating Rewrites: advanced_api_defaults.md
- API:
  - The API: api.md
  - Constructing Images: images.md
  - Events:
    - /api/v1/events: api_events_events.md
    - /api/v1/events/[:id]/dates: api_events_dates.md
    - /api/v1/venues: api_events_venues.md
    - /api/v1/theaters: api_events_theaters.md
    - /api/v1/event_categories: api_events_categories.md
    - /api/v1/event_tags: api_events_tags.md
    - /api/v1/movies: api_events_movies.md
    - /api/v1/showtimes: api_events_showtimes.md
  - Geography:
    - /api/v1/neighborhoods: api_places_neighborhoods.md
  - Stories:
    - /api/v1/stories: api_content_stories.md
  - Gameplan (Sports):
    - /api/v1/sports: api_stats_sports.md
    - /api/v1/standings: api_stats_standings.md
    - /api/v1/games: api_stats_games.md
    - /api/v1/teams: api_stats_teams.md
    - /api/v1/players: api_stats_players.md
    - /api/v1/schools: api_stats_schools.md
- Widgets:
  - Creating widgets: widgets.md
  - Examples:
    - Events List: widgets_example_events.md