site_name: Pointslocal Admin Documentation

pages:
- Home: index.md
- Creating Pages:
  - Stream Templates: mediastream_templates.md
- Events:
  - Managing Events: events_events.md
  - Exporting Events: events_exports.md
  - Other Content Types:
      - Sports: sports_exports.md
- API:
  - The API: api.md
  - Events:
    - /api/v1/events: api_events_events.md
    - /api/v1/venues: api_events_venues.md
    - /api/v1/event_categories: api_events_categories.md
    - /api/v1/event_tags: api_events_tags.md
  - Sports:
    - /api/v1/sports: api_stats_sports.md