site_name: Pointslocal Admin Documentation

pages:
- Home: index.md
- Creating Pages:
  - Stream Templates: mediastream_templates.md
- Events:
  - Managing Events: events_events.md
  - Exporting Events: events_exports.md
  - Other Content Types:
      - Sports: sports_exports.md
- API:
  - The API: api.md
  - Constructing Images: images.md
  - Events:
    - /api/v1/events: api_events_events.md
    - /api/v1/venues: api_events_venues.md
    - /api/v1/event_categories: api_events_categories.md
    - /api/v1/event_tags: api_events_tags.md
  - Stories:
    - /api/v1/stories: api_content_stories.md
  - Sports:
    - /api/v1/sports: api_stats_sports.md
    - /api/v1/standings: api_stats_standings.md
    - /api/v1/games: api_stats_games.md
    - /api/v1/teams: api_stats_teams.md
    - /api/v1/players: api_stats_players.md
    - /api/v1/schools: api_stats_schools.md
- Widgets:
  - Creating widgets: widgets.md
  - Examples:
    - Events List: widgets_example_events.md